---
- name: Testing Secret with ansible-vault
  hosts: servera
  vars_files:
    - vars/vault.yaml
  tasks:
    - name: Task 1
      debug:
        msg:
          - username is {{ username }}
          - password is {{ password }}
...
