---
- name: Testing forks
  hosts: all
  gather_facts: false
  tasks:
    - name: Task 1 - Wait for 5 seconds
      command: sleep 5

    - name: Task 2
      debug:
        msg: Task 2

    - name: Task 3 - Wait for 3 seconds
      command: sleep 3
...
