---
- name: Testing Handlers
  hosts: servera
  force_handlers: true
  tasks:
    - name: Task 1
      debug:
        msg: Task 1
      changed_when: true
      notify: 
        - Hand C

    - name: Task 2
      debug:
        msg: Task 2
      changed_when: true
      failed_when: true
      #ignore_errors: true
      notify:
        - myhand a
        - Hand C

    - name: Task 3
      debug:
        msg: Task 3
      changed_when: true
      notify:
        - doitB

  handlers:
    - name: myhand a
      debug:
        msg: Handler A

    - name: doitB
      debug:
        msg: Handler B

    - name: Hand C
      debug:
        msg: Handler C
...
