---
- name: Testing extra
  hosts: all
  tasks:
    - name: Task 1
      debug:
        msg: Task 1
      when: inventory_hostname == 'servera'

    - name: Task 2
      debug:
        msg: Task 2
      when: inventory_hostname == 'serverb'

    - block:
        - name: Task 3
          debug:
            msg: Task 3

        - name: Task 4
          debug:
            msg: Task 4
      when: inventory_hostname in groups['webservers']

    - name: Task 5
      debug:
        msg: Task 5
...

